// Convert a [lon,lat] GeoJSON (Natural Earth 110m land, public domain) into a
// single SVG path in equirectangular projection: x = lon+180, y = 90-lat,
// matching the map's viewBox "0 0 360 180". Run: node scripts/gen-world.mjs <geojson>
import { readFileSync, writeFileSync } from "node:fs";

const gj = JSON.parse(readFileSync(process.argv[2], "utf8"));
const r = (n) => Math.round(n * 10) / 10; // 0.1° precision — sub-pixel at map size

function ring(coords) {
  let d = "";
  for (let i = 0; i < coords.length; i++) {
    const [lon, lat] = coords[i];
    d += (i === 0 ? "M" : "L") + r(lon + 180) + " " + r(90 - lat) + " ";
  }
  return d + "Z";
}

const paths = [];
for (const f of gj.features) {
  const g = f.geometry;
  if (g.type === "Polygon") g.coordinates.forEach((rg) => paths.push(ring(rg)));
  else if (g.type === "MultiPolygon")
    g.coordinates.forEach((poly) => poly.forEach((rg) => paths.push(ring(rg))));
}

const d = paths.join(" ");
writeFileSync(
  new URL("../src/worldLand.ts", import.meta.url),
  `// Auto-generated by scripts/gen-world.mjs from Natural Earth 110m land\n` +
    `// (public domain). Equirectangular: x = lon+180, y = 90-lat.\n` +
    `export const WORLD_LAND = ${JSON.stringify(d)};\n`
);
console.log("rings:", paths.length, "| path chars:", d.length);
